### ISSUE TITLE
Conditionally ignore mavenRepo for snapshots

### ISSUE THREAD

**Issue by bjuric** [gwen-interpreter/gwen-web-npm#58]
If the gwen `version` ends in `-SNAPSHOT` and the `mavenRepo` setting does not contain the literal `snapshot` (case insensitive) anywhere in its path, then use the default snapshot repo, otherwise use the configured `mavenRepo` for the snapshot.

**Comment by Sorixelle** [comment]
Would there ever be a situation where someone has published a snapshot artifact to a repo without "snapshot" in the URL? Not very familiar with Maven conventions, so just making sure.

**Comment by bjuric** [comment]
It's a general maven convention and would be extremely rare. For example, Sonatype Nexus uses the following URL for all Gwen snapshots by default: https://oss.sonatype.org/content/repositories/snapshots/.

It's a good point, and it might be better to add another `mavenSnapshotRepo` setting instead that defaults to the current sonatype default if not configured. Perhaps go with that. It's standard to configure releases and snapshots separately in maven too.

**Comment by Sorixelle** [comment]
`mavenSnapshotRepo` option added in 1.2.0. Let me know if there are any issues.

**Comment by bjuric** [comment]
Verified and working. Thanks
