### ISSUE TITLE
Semver ranges for gwenWeb version

### ISSUE THREAD

**Issue by bjuric** [gwen-interpreter/gwen-web-npm#81]
Currently, we cannot specify for example `^3` as the gwenWeb version. This would allow a breaking v4 release without immediately impacting current v3 users who might have `latest` configured as the version.

Also, would be good to have an env var so users can optionally override the version at a system level.

**Comment by Sorixelle** [comment]
Both semver range support and environment variable overriding have been added in v2.1.0
